version: '3.8'

services:
  file-manager:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: web-file-manager
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - SESSION_SECRET=${SESSION_SECRET:-file-manager-secret-key-change-this}
      - NODE_ENV=production
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-0}  # 0 = unlimited
      - UPLOAD_TIMEOUT=${UPLOAD_TIMEOUT:-300000}  # 5 minutes
    volumes:
      # Windows-compatible volume binding with read-write permissions
      # Change the host path as needed for your Windows system
      # Example: - "C:/Users/YourUsername/file-manager-data:/app/uploads"
      - "./uploads:/app/uploads:rw"
      # Optional: Mount additional storage
      # - "./storage:/app/storage:rw"
    restart: unless-stopped
    networks:
      - file-manager-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-manager.rule=Host(`filemanager.localhost`)"
      - "traefik.http.services.file-manager.loadbalancer.server.port=3000"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 512M

networks:
  file-manager-network:
    driver: bridge
    name: file-manager-net

# Optional: Named volumes for persistent data
volumes:
  file_manager_uploads:
    driver: local
    name: file-manager-uploads