version: '3.8'

services:
  file-manager:
    image: rickicode/web-filemanager:latest
    container_name: web-file-manager-host
    network_mode: host
    environment:
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
      - AUTH=${AUTH:-true}  # Set to false to disable authentication
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - SESSION_SECRET=${SESSION_SECRET:-file-manager-secret-key-change-this}
      - NODE_ENV=production
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-0}  # 0 = unlimited
      - UPLOAD_TIMEOUT=${UPLOAD_TIMEOUT:-300000}  # 5 minutes
    volumes:
      # Host network mode - direct volume binding
      - "./uploads:/app/uploads:rw"
      # Optional: Mount additional storage
      # - "./storage:/app/storage:rw"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 512M

# Note: When using host network mode:
# - The container uses the host's network stack directly
# - No port mapping is needed
# - The application will be accessible on the host's IP address
# - Custom networks are not supported with host mode